### PR TITLE
Patched to be compatible with nan v2.0.9

### LINKED ISSUE #58: Node 4.0 compatibility
It seems this project is not currently working with node 4.0, I can provide the npm-debug.log if needed but after doing some digging i found it appears the main problem is it needs to be updated to NAN 2.x

### PR DESCRIPTION
**Pull request by jacobalberty**
Nan v2.0 or newer is needed to work with the new Node v4.0. This PR includes patches to work with Nan v2.0.9 and is confirmed to work with v4.0, should probably be tested with v0.12 as well before merge 

Edit: This pull request fixes #58

### CODE REVIEW

**Comment by xdenser** [comment]
Compiles but tests do not pass for me under ubuntu 15.04, server on windows.
I'll try to look at it next week.

**Comment by agebrock** [comment]
Getting a lot of those: 
*** set a breakpoint in malloc_error_break to debug
node(16520,0x7fff772f4300) malloc: *** error for object 0x102831928: pointer being freed was not allocated

**Comment by jacobalberty** [comment]
Yeah I did some investigation with valgrind and it looks like pointers are
being changed, I've been pouring over the documentation for nan to try and
understand what's going on, its slow. From what I can tell something is
changing the pointers and when the garbage collector hits it uses those
modified pointers, which makes no sense to me at all.

**Comment by jacobalberty** [comment]
That should be it, all tests pass up to events and for me they still trigger multiple events no matter what version of node-firebird-libfbclient and node combination i use.

**Comment by jacobalberty** [comment]
Just figured i'd note none of the breaking changes in node 5.0 seem to break these patches so equally compatible with node 4.2 and 5.0

**Comment by ingumsky** [comment]
The pull request is still not merged with the main repo but the changes jacobalberty suggested work like a charm for me on a number of projects. xdenser could you please merge it?

**Comment by ingumsky** [comment]
Thank you!

**Comment by mariuz** [comment]
@xdenser could you also push to npm a new version , thank you 👍

**Pull request merged**
